on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Decode keystore
        run: echo "$KEYSTORE_FILE" | base64 --decode > my-release-key.keystore

      - name: Upgrade Buildozer
        run: pip install --upgrade buildozer

      - name: Clean Build Cache
        run: buildozer android clean

      - name: Build AAB
        uses: digreatbrian/buildozer-action@v2
        with:
          python-version: 3.8
          buildozer-cmd: buildozer -v android release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: |
            ./bin/*.apk
            ./bin/*.aab
