on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upgrade Buildozer
        run: pip install --upgrade buildozer

      - name: Clean Build Cache
        run: buildozer android clean

      - name: Build AAB
        run: buildozer -v android release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: |
            ./bin/*.apk
            ./bin/*.aab
