name: Build Kivy Android App

on:
  push:
    branches:
      - main  # Ganti dengan cabang yang sesuai
  pull_request:
    branches:
      - main  # Ganti dengan cabang yang sesuai

jobs:
  build:
    runs-on: ubuntu-latest  # Menggunakan mesin Ubuntu terbaru

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Versi Python yang sesuai dengan project Anda

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libffi-dev
        sudo apt-get install -y python3-dev build-essential

    - name: Install pip dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build with Buildozer
      run: |
        # Install Buildozer dan dependensi terkait
        pip install buildozer
        buildozer android debug

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: android-debug-apk
        path: bin/*.apk  # Lokasi APK hasil build

