name: Build Kivy Android App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python (ensure version 3.9 or higher)
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Step 3: Install system dependencies (including libffi-dev)
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libffi-dev

    # Step 4: Install dependencies from requirements.txt
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    # Step 5: Install Buildozer
    - name: Install Buildozer
      run: |
        pip install buildozer

    # Step 6: Build the Android app using Buildozer
    - name: Build Android app
      run: |
        buildozer -v android debug

    # Optional: Step 7: Upload the APK as an artifact
    - name: Upload APK artifact
      uses: actions/upload-artifact@v2
      with:
        name: android-apk
        path: bin/*.apk
